### ISSUE TITLE
Lev.1 친구 목록 UI 구현

### ISSUE THREAD

**Issue by dkswlgus0314** [dkswlgus0314/PokeContactsAPP#1]
## 💡추가할 기능
<img width="267" alt="image" src="https://github.com/user-attachments/assets/074f5bcb-fc98-47be-9c7e-bd30187e0553">

## 🌿  To-do
- [] `UILabel`, `UITableView`, `UIButton` 을 이용해서 기본적인 UI 를 구성한다.
- [] `UITableViewCell` 에는 프로필 이미지를 보여줄 `UIImageView` 와 이름을 보여줄 `UILabel` , 전화번호를 표시할 `UILabel` 을 넣는다. 
- [] 프로필 이미지는 원모양이 되도록 한다.
- [] “추가” 버튼을 우상단에 위치시킨다.
- [] Cell 의 높이는 80으로 지정한다.
